# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
- script: dotnet build --configuration $(buildConfiguration)
  displayName: '.NET Core build $(buildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: '.NET Core publish $(buildConfiguration)'
  inputs:
    command: 'publish'
    publishWebProjects: true
    arguments: '--configuration $(buildConfiguration)'

- task: Docker@2
  displayName: 'Build Docker container & Push container to registry'
  inputs:
    containerRegistry: 'ewdev'
    repository: 'vdc/aspnet-core-sqldb'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    tags: |
      $(Build.BuildId)
      latest

- task: ArchiveFiles@2
  displayName: 'Create ZipDeploy package'
  inputs:
    rootFolderOrFile: '$(Build.SourcesDirectory)'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/ZipDeploy.zip'
    replaceExistingArchive: true

- task: PublishPipelineArtifact@1
  displayName: 'Publish .NET binaries as pipeline artefacts'
  inputs:
    targetPath: '$(Pipeline.Workspace)'
    artifact: 'aspnetcoresql'
    publishLocation: 'pipeline'


- task: AzureWebApp@1
  inputs:
    azureSubscription: 'Microsoft Azure Internal Consumption Eric van Wijk (84c1a2c7-585a-4753-ad28-97f69618cf12)'
    appType: 'webApp'
    appName: 'vdc-dev-paasapp-updj-appsvc-app'
    package: '$(System.DefaultWorkingDirectory)/**/*.zip'
    deploymentMethod: 'auto'